spring:
  application:
    name: discovery-service
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:

  endpoints:

    web:

      exposure:

        include: "*"

  endpoint:

    health:

      show-details: always

    prometheus:

      access: unrestricted

  metrics:

    tags:

      application: ${spring.application.name}

    distribution:

      percentiles-histogram:

        http.server.requests: true

  prometheus:

    metrics:

      export:

        enabled: true

  observations:

    annotations:

      enabled: true

  info:

    env:

      enabled: true