server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import:
      - optional:file:../../.env[.properties]
      - optional:file:.env[.properties]
  main:
    web-application-type: reactive
  datasource:
    url: ${GATEWAY_SERVICE_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${GATEWAY_SERVICE_DB_NAME:gateway_service_db}}
    username: ${GATEWAY_SERVICE_DB_USERNAME:${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:postgres}}}
    password: ${GATEWAY_SERVICE_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:postgres}}}

  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    #    username: vanhnekdungso74@gmail.com
    #    password: odbv zeup ignq lagi
    username: ${MAIL_USERNAME:hieeusbs05@gmail.com}
    password: ${MAIL_PASSWORD:xlgvamvkrwuattsc}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
      timeout: 6000

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**,/courses/**

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**,/categories,/lesson/**,/sublessons/**,/category/**,/revenue-categories,/sublesson/**

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/enrollments/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secretKey: ZGV2LW9ubHktY291cnNlZGVteS1qd3Qtc2VjcmV0LTEyMzQ1Ng==
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION:3600000} # 1 giờ
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION:2592000000} # 30 ngày

fe:
  url: ${FRONTEND_URL:http://localhost:3000}
api:
  prefix:
