-- Run this in Supabase SQL Editor.
-- It creates one PostgreSQL schema per CourseDemy microservice and the
-- service-owned tables that match the current JPA entity model.

create schema if not exists auth_service_db;
create schema if not exists user_service_db;
create schema if not exists course_service_db;
create schema if not exists order_service_db;
create schema if not exists payment_service_db;
create schema if not exists enrollment_service_db;
create schema if not exists notification_service_db;

-- =========================
-- Auth/Gateway service
-- =========================

create table if not exists auth_service_db.roles (
  id integer generated by default as identity primary key,
  role_name varchar(255) not null,
  description text,
  constraint uk_gateway_roles_role_name unique (role_name)
);

create table if not exists auth_service_db.users (
  id bigint generated by default as identity primary key,
  username varchar(255),
  email varchar(255) not null,
  password varchar(255),
  phone_number varchar(255),
  avatar_url varchar(255),
  description text,
  facebook_link varchar(255),
  youtube_link varchar(255),
  is_active integer not null default 1,
  created_at timestamp,
  updated_at timestamp,
  deleted_at timestamp,
  role_id integer not null references auth_service_db.roles(id),
  constraint uk_gateway_users_email unique (email)
);

-- =========================
-- User service
-- =========================

create table if not exists user_service_db.roles (
  id bigint generated by default as identity primary key,
  role_name varchar(255) not null,
  description text,
  constraint uk_user_roles_role_name unique (role_name)
);

create table if not exists user_service_db.users (
  id bigint generated by default as identity primary key,
  username varchar(255),
  email varchar(255) not null,
  password varchar(255),
  phone_number varchar(255),
  avatar_url varchar(255),
  description text,
  facebook_link varchar(255),
  youtube_link varchar(255),
  is_active integer not null default 1,
  created_at timestamp,
  updated_at timestamp,
  deleted_at timestamp,
  role_id bigint not null references user_service_db.roles(id),
  constraint uk_user_users_email unique (email)
);

create table if not exists user_service_db.users_courses (
  id bigint generated by default as identity primary key,
  user_id bigint not null references user_service_db.users(id),
  course_id bigint not null,
  progress bigint not null default 0,
  registered_at timestamp,
  constraint uk_user_user_course unique (user_id, course_id)
);

-- =========================
-- Course service
-- =========================

create table if not exists course_service_db.categories (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  constraint uk_course_category_name unique (name)
);

create table if not exists course_service_db.courses (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  description text,
  price numeric(15, 2) not null default 0,
  level integer not null default 0,
  quantity integer not null default 0,
  created_at timestamp,
  updated_at timestamp,
  category_id bigint references course_service_db.categories(id),
  teacher_id bigint not null
);

create table if not exists course_service_db.course_image (
  id bigint generated by default as identity primary key,
  image_url varchar(255) not null,
  course_id bigint not null unique references course_service_db.courses(id)
);

create table if not exists course_service_db.courses_detail (
  id bigint generated by default as identity primary key,
  content text,
  course_include text,
  request text,
  description text,
  course_id bigint not null unique references course_service_db.courses(id)
);

create table if not exists course_service_db.lessons (
  id bigint generated by default as identity primary key,
  title varchar(255),
  order_index bigint,
  course_id bigint references course_service_db.courses(id)
);

create table if not exists course_service_db.sub_lessons (
  id bigint generated by default as identity primary key,
  title varchar(255),
  video_url varchar(255),
  duration bigint,
  order_index bigint,
  lesson_id bigint references course_service_db.lessons(id)
);

create table if not exists course_service_db.materials (
  id integer generated by default as identity primary key,
  title varchar(255),
  file_link varchar(255),
  "sublessonEntity_id" bigint references course_service_db.sub_lessons(id)
);

create table if not exists course_service_db.comments (
  id bigint generated by default as identity primary key,
  comment text,
  status integer,
  parent_id bigint,
  created_at timestamp,
  updated_at timestamp,
  user_id bigint,
  sub_lesson_id bigint references course_service_db.sub_lessons(id)
);

create table if not exists course_service_db.comment_likes (
  id bigint generated by default as identity primary key,
  likes integer,
  created_at timestamp,
  user_id bigint,
  comment_id bigint references course_service_db.comments(id)
);

create table if not exists course_service_db.reviews (
  id bigint generated by default as identity primary key,
  rating double precision,
  created_at timestamp,
  updated_at timestamp,
  comment text,
  status integer,
  parent_id bigint,
  user_id bigint not null,
  course_id bigint references course_service_db.courses(id)
);

create table if not exists course_service_db.review_likes (
  id bigint generated by default as identity primary key,
  likes integer,
  created_at timestamp,
  user_id bigint,
  review_id bigint references course_service_db.reviews(id)
);

-- =========================
-- Order service
-- =========================

create table if not exists order_service_db.cart (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique
);

create table if not exists order_service_db.cart_item (
  id bigint generated by default as identity primary key,
  price double precision,
  cart_id bigint references order_service_db.cart(id),
  course_id bigint not null
);

create table if not exists order_service_db.orders (
  id bigint generated by default as identity primary key,
  total_price double precision,
  status varchar(255),
  created_at timestamp,
  payment_method varchar(255),
  payment_time timestamp,
  user_id bigint not null
);

create table if not exists order_service_db.orders_detail (
  id bigint generated by default as identity primary key,
  price double precision,
  order_id bigint references order_service_db.orders(id),
  course_id bigint not null
);

-- =========================
-- Payment service
-- =========================
-- Current code updates order/payment data through order-like entities.
-- Keep a minimal payment event table for gateway callbacks and audits.

create table if not exists payment_service_db.payment_events (
  id bigint generated by default as identity primary key,
  order_id bigint,
  provider varchar(255),
  transaction_no varchar(255),
  amount numeric(15, 2),
  status varchar(255),
  raw_payload jsonb,
  created_at timestamp default now()
);

-- =========================
-- Enrollment service
-- =========================

create table if not exists enrollment_service_db.users_courses (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  course_id bigint not null,
  progress bigint default 0,
  registered_at timestamp default now(),
  constraint uk_enrollment_user_course unique (user_id, course_id)
);

-- =========================
-- Notification service
-- =========================

create table if not exists notification_service_db.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  title varchar(255) not null,
  content text,
  type varchar(255),
  is_read boolean not null default false,
  created_at timestamp default now()
);

create index if not exists idx_auth_users_role_id on auth_service_db.users(role_id);
create index if not exists idx_user_users_role_id on user_service_db.users(role_id);
create index if not exists idx_user_courses_user_id on user_service_db.users_courses(user_id);
create index if not exists idx_course_courses_category_id on course_service_db.courses(category_id);
create index if not exists idx_course_lessons_course_id on course_service_db.lessons(course_id);
create index if not exists idx_course_sub_lessons_lesson_id on course_service_db.sub_lessons(lesson_id);
create index if not exists idx_order_orders_user_id on order_service_db.orders(user_id);
create index if not exists idx_order_details_order_id on order_service_db.orders_detail(order_id);
create index if not exists idx_payment_events_order_id on payment_service_db.payment_events(order_id);
create index if not exists idx_enrollment_user_course_user_id on enrollment_service_db.users_courses(user_id);
create index if not exists idx_notification_user_id on notification_service_db.notifications(user_id);
