-- Run this in Supabase SQL Editor.
-- It creates one PostgreSQL schema per CourseDemy microservice and the
-- service-owned tables that match the current JPA entity model.

create schema if not exists auth_service_db;
create schema if not exists user_service_db;
create schema if not exists course_service_db;
create schema if not exists order_service_db;
create schema if not exists payment_service_db;
create schema if not exists enrollment_service_db;
create schema if not exists notification_service_db;

-- =========================
-- Auth/Gateway service
-- =========================

create table if not exists auth_service_db.roles (
  id integer generated by default as identity primary key,
  role_name varchar(255) not null,
  description text,
  constraint uk_gateway_roles_role_name unique (role_name)
);

create table if not exists auth_service_db.users (
  id bigint generated by default as identity primary key,
  username varchar(255),
  email varchar(255) not null,
  password varchar(255),
  phone_number varchar(255),
  avatar_url varchar(255),
  description text,
  facebook_link varchar(255),
  youtube_link varchar(255),
  is_active integer not null default 1,
  created_at timestamp,
  updated_at timestamp,
  deleted_at timestamp,
  role_id integer not null references auth_service_db.roles(id),
  constraint uk_gateway_users_email unique (email)
);

-- =========================
-- User service
-- =========================

create table if not exists user_service_db.roles (
  id bigint generated by default as identity primary key,
  role_name varchar(255) not null,
  description text,
  constraint uk_user_roles_role_name unique (role_name)
);

create table if not exists user_service_db.users (
  id bigint generated by default as identity primary key,
  username varchar(255),
  email varchar(255) not null,
  password varchar(255),
  phone_number varchar(255),
  avatar_url varchar(255),
  description text,
  facebook_link varchar(255),
  youtube_link varchar(255),
  is_active integer not null default 1,
  created_at timestamp,
  updated_at timestamp,
  deleted_at timestamp,
  role_id bigint not null references user_service_db.roles(id),
  constraint uk_user_users_email unique (email)
);

create table if not exists user_service_db.users_courses (
  id bigint generated by default as identity primary key,
  user_id bigint not null references user_service_db.users(id),
  course_id bigint not null,
  progress bigint not null default 0,
  registered_at timestamp,
  constraint uk_user_user_course unique (user_id, course_id)
);

-- =========================
-- Course service
-- =========================

create table if not exists course_service_db.categories (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  constraint uk_course_category_name unique (name)
);

create table if not exists course_service_db.courses (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  description text,
  price numeric(15, 2) not null default 0,
  level integer not null default 0,
  quantity integer not null default 0,
  created_at timestamp,
  updated_at timestamp,
  category_id bigint references course_service_db.categories(id),
  teacher_id bigint not null
);

create table if not exists course_service_db.course_image (
  id bigint generated by default as identity primary key,
  image_url varchar(255) not null,
  course_id bigint not null unique references course_service_db.courses(id)
);

create table if not exists course_service_db.courses_detail (
  id bigint generated by default as identity primary key,
  content text,
  course_include text,
  request text,
  description text,
  course_id bigint not null unique references course_service_db.courses(id)
);

create table if not exists course_service_db.lessons (
  id bigint generated by default as identity primary key,
  title varchar(255),
  order_index bigint,
  course_id bigint references course_service_db.courses(id)
);

create table if not exists course_service_db.sub_lessons (
  id bigint generated by default as identity primary key,
  title varchar(255),
  video_url varchar(255),
  duration bigint,
  order_index bigint,
  lesson_id bigint references course_service_db.lessons(id)
);

create table if not exists course_service_db.materials (
  id integer generated by default as identity primary key,
  title varchar(255),
  file_link varchar(255),
  "sublessonEntity_id" bigint references course_service_db.sub_lessons(id)
);

create table if not exists course_service_db.comments (
  id bigint generated by default as identity primary key,
  comment text,
  status integer,
  parent_id bigint,
  created_at timestamp,
  updated_at timestamp,
  user_id bigint,
  sub_lesson_id bigint references course_service_db.sub_lessons(id)
);

create table if not exists course_service_db.comment_likes (
  id bigint generated by default as identity primary key,
  likes integer,
  created_at timestamp,
  user_id bigint,
  comment_id bigint references course_service_db.comments(id)
);

create table if not exists course_service_db.reviews (
  id bigint generated by default as identity primary key,
  rating double precision,
  created_at timestamp,
  updated_at timestamp,
  comment text,
  status integer,
  parent_id bigint,
  user_id bigint not null,
  course_id bigint references course_service_db.courses(id)
);

create table if not exists course_service_db.review_likes (
  id bigint generated by default as identity primary key,
  likes integer,
  created_at timestamp,
  user_id bigint,
  review_id bigint references course_service_db.reviews(id)
);

-- =========================
-- Order service
-- =========================

create table if not exists order_service_db.cart (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique
);

create table if not exists order_service_db.cart_item (
  id bigint generated by default as identity primary key,
  price double precision,
  cart_id bigint references order_service_db.cart(id),
  course_id bigint not null
);

create table if not exists order_service_db.orders (
  id bigint generated by default as identity primary key,
  total_price double precision,
  status varchar(255),
  created_at timestamp,
  payment_method varchar(255),
  payment_time timestamp,
  user_id bigint not null
);

create table if not exists order_service_db.orders_detail (
  id bigint generated by default as identity primary key,
  price double precision,
  order_id bigint references order_service_db.orders(id),
  course_id bigint not null
);

-- =========================
-- Payment service
-- =========================
-- Current code updates order/payment data through order-like entities.
-- Keep a minimal payment event table for gateway callbacks and audits.

create table if not exists payment_service_db.payment_events (
  id bigint generated by default as identity primary key,
  order_id bigint,
  provider varchar(255),
  transaction_no varchar(255),
  amount numeric(15, 2),
  status varchar(255),
  raw_payload jsonb,
  created_at timestamp default now()
);

-- =========================
-- Enrollment service
-- =========================

create table if not exists enrollment_service_db.users_courses (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  course_id bigint not null,
  progress bigint default 0,
  registered_at timestamp default now(),
  constraint uk_enrollment_user_course unique (user_id, course_id)
);

-- =========================
-- Notification service
-- =========================

create table if not exists notification_service_db.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  title varchar(255) not null,
  content text,
  type varchar(255),
  is_read boolean not null default false,
  created_at timestamp default now()
);

create index if not exists idx_auth_users_role_id on auth_service_db.users(role_id);
create index if not exists idx_user_users_role_id on user_service_db.users(role_id);
create index if not exists idx_user_courses_user_id on user_service_db.users_courses(user_id);
create index if not exists idx_course_courses_category_id on course_service_db.courses(category_id);
create index if not exists idx_course_lessons_course_id on course_service_db.lessons(course_id);
create index if not exists idx_course_sub_lessons_lesson_id on course_service_db.sub_lessons(lesson_id);
create index if not exists idx_order_orders_user_id on order_service_db.orders(user_id);
create index if not exists idx_order_details_order_id on order_service_db.orders_detail(order_id);
create index if not exists idx_payment_events_order_id on payment_service_db.payment_events(order_id);
create index if not exists idx_enrollment_user_course_user_id on enrollment_service_db.users_courses(user_id);
create index if not exists idx_notification_user_id on notification_service_db.notifications(user_id);

-- =============================================================================
-- SEED DATA (Dữ liệu mẫu ban đầu)
-- =============================================================================

-- 1. Roles cho Auth Service & User Service
insert into auth_service_db.roles (id, role_name, description)
values 
  (1, 'ADMIN', 'Quản trị hệ thống'),
  (2, 'TEACHER', 'Giảng viên'),
  (3, 'STUDENT', 'Học viên')
on conflict (role_name) do nothing;

insert into user_service_db.roles (id, role_name, description)
values 
  (1, 'ADMIN', 'Quản trị hệ thống'),
  (2, 'TEACHER', 'Giảng viên'),
  (3, 'STUDENT', 'Học viên')
on conflict (role_name) do nothing;

-- 2. Tài khoản test mẫu (Password: 123456)
insert into auth_service_db.users (id, username, email, password, role_id, is_active, created_at, updated_at)
values 
  (1, 'Admin Test', 'admin@coursedemy.local', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 1, 1, now(), now()),
  (2, 'Teacher Test', 'teacher@coursedemy.local', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 2, 1, now(), now()),
  (3, 'Student Test', 'student@coursedemy.local', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 3, 1, now(), now())
on conflict (email) do nothing;

insert into user_service_db.users (id, username, email, password, role_id, is_active, created_at, updated_at)
values 
  (1, 'Admin Test', 'admin@coursedemy.local', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 1, 1, now(), now()),
  (2, 'Teacher Test', 'teacher@coursedemy.local', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 2, 1, now(), now()),
  (3, 'Student Test', 'student@coursedemy.local', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', 3, 1, now(), now())
on conflict (email) do nothing;

-- 3. Danh mục khóa học mẫu
insert into course_service_db.categories (id, name, description)
values 
  (1, 'Frontend Development', 'Các khóa học lập trình giao diện người dùng hiện đại'),
  (2, 'Backend Development', 'Các khóa học lập trình máy chủ, cơ sở dữ liệu và API'),
  (3, 'Fullstack Web', 'Khóa học kết hợp toàn diện cả Frontend và Backend'),
  (4, 'Mobile App Development', 'Lập trình ứng dụng di động đa nền tảng Flutter & React Native'),
  (5, 'DevOps & Cloud', 'Kiến trúc hệ thống, Docker, Kubernetes và CI/CD'),
  (6, 'AI & Data Science', 'Trí tuệ nhân tạo, Machine Learning và Khoa học dữ liệu')
on conflict (name) do nothing;

-- 4. Khóa học mẫu
insert into course_service_db.courses (id, title, description, price, level, quantity, category_id, teacher_id, created_at, updated_at)
values 
  (1, 'Lập trình React & Next.js chuyên sâu', 'Khóa học làm chủ React 19, Next.js App Router, SSR, TailwindCSS từ cơ bản đến nâng cao.', 899000, 1, 120, 1, 2, now(), now()),
  (2, 'Xây dựng Microservices với Spring Boot & Docker', 'Thiết kế hệ thống phân tán, Spring Cloud Gateway, Eureka, Kafka, Docker & PostgreSQL.', 1299000, 2, 85, 2, 2, now(), now()),
  (3, 'Mastering Fullstack Web với Next.js & Java', 'Lộ trình Fullstack thực chiến từ thiết kế giao diện đến tối ưu hệ thống doanh nghiệp.', 1599000, 2, 210, 3, 2, now(), now()),
  (4, 'Lập trình ứng dụng di động Flutter từ Zero đến Hero', 'Xây dựng ứng dụng iOS & Android mượt mà với Flutter và Firebase.', 799000, 1, 95, 4, 2, now(), now()),
  (5, 'Docker & Kubernetes cho Developers', 'Làm chủ container hóa ứng dụng và triển khai hệ thống quy mô lớn.', 990000, 2, 60, 5, 2, now(), now()),
  (6, 'Trí tuệ nhân tạo & Prompt Engineering với Python', 'Ứng dụng Generative AI, LLMs, LangChain và Python trong các dự án thực tế.', 1190000, 1, 150, 6, 2, now(), now())
on conflict do nothing;

-- 5. Bài học & Chương mẫu (Lessons & Sublessons)
insert into course_service_db.lessons (id, title, order_index, course_id)
values 
  (1, 'Chương 1: Giới thiệu & Cài đặt môi trường', 1, 1),
  (2, 'Chương 2: React Server Components & Routing', 2, 1),
  (3, 'Chương 3: Tối ưu hiệu năng & Triển khai', 3, 1),
  (4, 'Chương 1: Kiến trúc Microservices phân tán', 1, 2)
on conflict do nothing;

insert into course_service_db.sub_lessons (id, title, video_url, duration, order_index, lesson_id)
values 
  (1, '1.1 Tổng quan về React 19 & Next.js App Router', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 600, 1, 1),
  (2, '1.2 Thiết lập dự án với TailwindCSS & TypeScript', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', 900, 2, 1),
  (3, '2.1 Server Components vs Client Components', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 1200, 1, 2),
  (4, '2.2 Quản lý State và Data Fetching với Cache', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 1500, 2, 2),
  (5, '3.1 Server Actions & Form Handling', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 1100, 1, 3),
  (6, '3.2 Deploy ứng dụng lên Vercel & Docker', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4', 1400, 2, 3),
  (7, '1.1 Phân tích Domain & Thiết kế Service Boundaries', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 800, 1, 4),
  (8, '1.2 Cấu hình Eureka Discovery & Spring Cloud Gateway', 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', 1300, 2, 4)
on conflict do nothing;


