<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot Parent -->
    <!--  Quyết định version  -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.6</version>
        <relativePath/>
    </parent>

    <!--  Pom Root -->
    <groupId>com.coursedemy</groupId>
    <artifactId>CourseDemy-Backend</artifactId>
    <version>1.0.0</version>

    <packaging>pom</packaging>

    <!--  Setup  -->
    <properties>
        <java.version>17</java.version>
        <coursedemy.common.version>0.0.1-SNAPSHOT</coursedemy.common.version>
        <spring-cloud.version>2025.0.0</spring-cloud.version>
        <modelmapper.version>3.2.0</modelmapper.version>
        <jjwt.version>0.11.5</jjwt.version>
        <cloudinary.version>1.33.0</cloudinary.version>
        <okhttp.version>4.11.0</okhttp.version>
        <gson.version>2.10.1</gson.version>
    </properties>

    <!--  Các module  -->
    <modules>
        <module>libs/common</module>
        <module>apps/gateway-service</module>
        <module>apps/discovery-service</module>
        <module>apps/user-service</module>
        <module>apps/course-service</module>
        <module>apps/order-service</module>
        <module>apps/payment-service</module>
        <module>apps/enrollment-service</module>
        <module>apps/notification-service</module>
    </modules>

    <!--  Các dependencies chung-->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
<!--            <dependency>-->
<!--                <groupId>com.coursedemy</groupId>-->
<!--                <artifactId>common</artifactId>-->
<!--                <version>${coursedemy.common.version}</version>-->
<!--            </dependency>-->
            <dependency>
                <groupId>org.modelmapper</groupId>
                <artifactId>modelmapper</artifactId>
                <version>${modelmapper.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-api</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-impl</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt-jackson</artifactId>
                <version>${jjwt.version}</version>
            </dependency>
            <dependency>
                <groupId>com.cloudinary</groupId>
                <artifactId>cloudinary-http44</artifactId>
                <version>${cloudinary.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <inherited>false</inherited>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
